### ISSUE TITLE
2021 Semester 2 Roadmap

### ISSUE THREAD

**Issue by duncanrhamill** [SUSF-Robotics-and-Software/phobos_sw#31]
Tasks to complete before competition:

## Locomotion

- [ ] `MechExec` - needed to be able to drive the physical rover, should be flexible to allow commanding of arm as well as locomotion
- [ ] Test functionality of localisation system

## Localisation

- [ ] Decide on new camera setup which allows:
  - Streaming low latency video from rover to ground control
  - Discrete requests for frames/disparity maps from navigation system
  - Continuous feed of rectified images into ORB_SLAM3 for position update
- [ ] Implement the above
- [ ] Test position accuracy/drift

## Navigation

- [ ] Point cloud generation and filtering
- [ ] DEM calculation
- [ ] CostMap calculation
- [ ] Path planning
- [ ] Test navigation capabilities

## Ground Control

- [ ] Finish web interface:
  - [ ] Video streams from cameras
  - [ ] Text telecommand issuing
  - [ ] Telemetry viewing
  - [ ] Controller interface
- [ ] Decide on controller map
